defaults:
  - data: default
  - trainer: default
  - model: tabular_classifier
  - optimizer: adam
  - paths: default
  - _self_
hydra:
  run:
    dir: ${paths.project_root}/models/${now:%Y%m%d_%H%M%S}/hydra
