workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-8
    acceleratorType: NVIDIA_TESLA_T4
    acceleratorCount: 1
  replicaCount: 1
  containerSpec:
    imageUri: europe-west4-docker.pkg.dev/diabetic-classification-484510/container-registry/train:latest
    env:
      - name: WANDB_API_KEY
        value: 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
baseOutputDirectory:
  outputUriPrefix: gs://vertex-ai-outputs-diabetes